name: SaxoFlow CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: 🐍 Set up Python and Virtualenv
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 🛠 Install System Dependencies (APT)
        run: |
          sudo apt-get update
          sudo apt-get install -y yosys iverilog gtkwave make
          pip install symbiyosys

      - name: 🧪 Python Environment + Editable Install
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -e .
          pip install flake8 pytest coverage

      - name: 🧹 Lint Python Code
        run: |
          source .venv/bin/activate
          flake8 saxoflow/ --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 saxoflow/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: 🧪 Run Unit Tests
        run: |
          source .venv/bin/activate
          pytest tests/ --tb=short -q

      - name: ✅ Check CLI Entry Points
        run: |
          source .venv/bin/activate
          bin/saxoflow --help
          bin/saxoflow doctor summary

      - name: 🔁 Validate Interactive Bootstrap (headless)
        run: |
          source .venv/bin/activate
          bin/saxoflow init-env --headless
          bin/saxoflow install selected

      - name: 🔁 Validate Preset Installs (minimal, fpga, asic, formal, full)
        run: |
          source .venv/bin/activate
          bin/saxoflow init-env --preset minimal
          bin/saxoflow init-env --preset fpga
          bin/saxoflow init-env --preset asic
          bin/saxoflow init-env --preset formal
          bin/saxoflow init-env --preset full

      - name: 🧪 Test Project Init
        run: |
          source .venv/bin/activate
          bin/saxoflow init test_project
          test -f test_project/rtl/.gitkeep
          test -f test_project/Makefile

      - name: 🧪 Validate Doctor Health Scan
        run: |
          source .venv/bin/activate
          bin/saxoflow doctor summary

      - name: 📊 Test Code Coverage (fail if <60%)
        run: |
          source .venv/bin/activate
          coverage run -m pytest tests/
          coverage report --fail-under=60 -m
